LoginApp/urls.py
from django.urls import path
from LoginApp import views


app_name = 'LoginApp'

urlpatterns = [
    path('signup/', views.signupView, name='signup'),
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
    path('profile/', views.user_profileView, name='profile'),    
]

TaskManagerProj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('LoginApp.urls')),
    path('', include('TasksApp.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TasksApp/urls.py
from django.urls import path
from TasksApp import views


app_name = 'TasksApp'

urlpatterns = [
    path('', views.addtaskView, name='add_task'),
    path('tasks/', views.tasklistView, name='task_list'),
    path('search/', views.searchtasksView, name='search_tasks'),
]

templates/footer.html
<footer class="bg-dark">
    <div class="container">
        <div class="row">
            <div class="col-12 text-white text-center pt-3">
                <p>All Copyright is preserved © To Md Sha Newaz</p>
                <p class="" id="dev_text">Developed by <a class="text-success" href="https://mdshanewaz.github.io/DarkBlackFire" target=”_blank”>Dev SAWON</a></p>
            </div>
        </div>
    </div>
</footer>

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title_block %}E-Commerence{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'img/favicon.jpg' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/scripts.js' %}"></script>
    <style>
        .card {
            height: 350px;
        }

        .card-product:after {
            content: "";
            display: table;
            clear: both;
            visibility: hidden;
        }

        .card-product .price_new, .card-product .price {
            margin-right: 5px;
        }

        .card-product .price-old {
            color: #999;
        }

        .card-product .img-wrap {
            border-radius: 3px 3px 0 0 ;
            overflow: hidden;
            position: relative;
            height: 220px;
            text-align: center;
        }

        .card-product .img-wrap img {
            max-height: 100%;
            max-width: 100%;
            object-fit: cover;
        }

        .card-product .info-wrap {
            overflow: hidden;
            padding: 15px;
            border-top: 1px solid #eee;
        }

        .card-product .action-wrap {
            padding-top: 4px;
            margin-top: 4px;
        }

        .card-product .bottom-wrap {
            padding: 15px;
            border-top: 1px solid #eee;
        }

        .card-product .title {
            margin-top: 0px;
        }

    </style>
</head>
<body>
    {% include 'navbar.html' %}

    <div class="container">
        <div class="messages mt-2">
            {% if messages %}
                {% for message in messages %}
                    <div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
                        {{ message }}
                        <button type="button" class="btn close" data-bs-dismiss="alert" aria-label="Close" style="float: right;">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            {% endif %} 
        </div>
        {% block body_block %}

        {% endblock %}
    </div>

    {% include 'footer.html' %}

    <script src="https://code.jquery.com/jquery-3.7.1.slim.min.js" integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js" integrity="sha512-2rNj2KJ+D8s1ceNasTIex6z4HWyOnEYLVC3FigGOmyQCZc2eBXKgOxQmo3oKLHyfcj53uz4QMsRCWNbLd32Q1g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'TasksApp:add_task' %}">FOODIES</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if request.user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fa-solid fa-user-tie"></i> {{ request.user.profile.username }}</a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'LoginApp:profile' %}">Profile</a></li>
              <li><a class="dropdown-item" href="{% url 'TasksApp:task_list' %}">Tasks</a></li>
              <li><a class="dropdown-item" href="{% url 'TasksApp:search_tasks' %}">Search Task</a></li>
                <div class="dropdown-divider">
                  
                </div>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'LoginApp:logout' %}">Logout</a></li>
            </ul>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="btn btn-primary" href="{% url 'LoginApp:login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
</nav>